name: CI - Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do Código
      uses: actions/checkout@v3

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Instalar Dependências
      run: npm ci || npm install

    - name: Corrigir Permissões de Execução
      run: chmod +x node_modules/.bin/*

    - name: Executar Testes Automatizados com Cobertura
      run: npm test